language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - sys-img-armeabi-v7a-android-25
    - extra-android-m2repository

script:
  - cd Roboti
  - ./gradlew 
